version: "3.7"

volumes:
  data:

services:
  app:
    build:
      context: ./src
      dockerfile: ./Dockerfile
    env_file: ./src/.env
    ports:
      - 8080:8080
      - 2345:2345
    volumes:
      - ./src:/app
  # db:
  #   image: postgres:12.4-alpine
  #   env_file: ./src/.env
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - ./src:/app
  #     - ./database:/db
  #     - ./.docker/postgres:/docker-entrypoint-initdb.d
